//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerPropertyPrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Report
    {

        public int MessageId { get; set; }
        public int ToUserId { get; set; }
        public int FromUserId { get; set; }
        public string Message { get; set; }
        public string ReportType { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }

    }
}
